services:
  db:
    container_name: postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: rachid
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  backend_api:
    container_name: backend_api
    image: rachidassouani/fullstackjava
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fullstackjava
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
